# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proto/category.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("app/proto/category.proto", syntax: :proto3) do
    add_message "plan.SubCategory" do
      optional :id, :uint64, 1
      optional :name, :string, 2
    end
    add_message "plan.ParentCategory" do
      optional :id, :uint64, 1
      optional :name, :string, 2
      repeated :subcategories, :message, 3, "plan.SubCategory"
    end
    add_message "plan.GetCategoriesResp" do
      repeated :data, :message, 1, "plan.ParentCategory"
    end
  end
end

module Plan
  SubCategory = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("plan.SubCategory").msgclass
  ParentCategory = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("plan.ParentCategory").msgclass
  GetCategoriesResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("plan.GetCategoriesResp").msgclass
end
