# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: app/proto/eat_plan.proto for package 'plan'

require 'grpc'

module Plan
  module EatPlanService
    class Service
      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'plan.EatPlanService'

      rpc :CreateEatPlan, ::Plan::CreateEatPlanReq, ::Plan::CreateEatPlanResp
      rpc :PublishEatPlan, ::Plan::ChangeStatusEatPlanReq, ::Google::Protobuf::Empty
      rpc :DraftEatPlan, ::Plan::ChangeStatusEatPlanReq, ::Google::Protobuf::Empty
    end

    Stub = Service.rpc_stub_class
  end
end
