# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/proto/eat_plan.proto

require 'google/protobuf'

require 'google/protobuf/empty_pb'
require 'google/protobuf/timestamp_pb'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("app/proto/eat_plan.proto", syntax: :proto3) do
    add_message "plan.EatPlanCategoryResp" do
      optional :id, :uint64, 1
      optional :name, :string, 2
    end
    add_message "plan.CreateEatPlanReq" do
      optional :name, :string, 1, json_name: "name"
      optional :description, :string, 2, json_name: "description"
      optional :duration_metric, :string, 3, json_name: "duration_metric"
      optional :duration_value, :uint32, 4, json_name: "duration_value"
      optional :meals_per_day, :uint32, 5, json_name: "meals_per_day"
      optional :user_id, :uint64, 6, json_name: "user_id"
      repeated :category_ids, :uint64, 7, json_name: "category_ids"
    end
    add_message "plan.ChangeStatusEatPlanReq" do
      optional :id, :uint64, 1
    end
    add_message "plan.EatPlan" do
      optional :id, :uint64, 1
      optional :name, :string, 2
      optional :description, :string, 3
      optional :status, :string, 4
      optional :duration_metric, :string, 5
      optional :duration_value, :uint32, 6
      optional :meals_per_day, :uint32, 7
      optional :user_id, :uint64, 8
      repeated :categories, :message, 9, "plan.EatPlanCategoryResp"
      optional :created_at, :message, 10, "google.protobuf.Timestamp"
      optional :updated_at, :message, 11, "google.protobuf.Timestamp"
    end
    add_message "plan.CreateEatPlanResp" do
      optional :data, :message, 1, "plan.EatPlan"
    end
  end
end

module Plan
  EatPlanCategoryResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("plan.EatPlanCategoryResp").msgclass
  CreateEatPlanReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("plan.CreateEatPlanReq").msgclass
  ChangeStatusEatPlanReq = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("plan.ChangeStatusEatPlanReq").msgclass
  EatPlan = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("plan.EatPlan").msgclass
  CreateEatPlanResp = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("plan.CreateEatPlanResp").msgclass
end
